# Exercise 2, Introduction to Python, part 2: variable types, syntax, and logic

Last class we got out feet wet. In class today, we'll work thorugh most of the key basics along with introducing our first two packages for data science: `numpy` and `scipy`.

We are essentially covering the core of the Python standard Library (this is what you are installing when you "install python"). [The doumentaion for all the tools included can be found here](https://docs.python.org/3.8/library/index.html). 

It's also worth noting that python is very forgiving for a lot of user decisions relating to formatting, naming, etc. but the community has decided on a set of standards documented in [Python Enhabncement Proposal 8 (aka PEP 8)](https://www.python.org/dev/peps/pep-0008/). It's worth taking a read, but there are a few things important conventions worth knowing:

1. names should reflect purpose not implimentation
2. indents are made with 4 spaces (not 2 spaces, not tabs)
3. variables, functions should be named all_lower_case_with_underscores
4. class objects should be named in CamelCase
5. packages should generally have short onewordlowercase names

In general, _any_ programming requires constantly checking the docs associated with the code. I usually keep tabs open to the documentation I need. For quick reference these can be found under `Help` in the menubar. 

In Jupyter you can also access the documentation for a function directly when you have typed by pressing `Shift-TAB` or opening the `Conetxtual Help` window. 

## Table of Contents

* [2.1 Python variable types](#python_types)
    * [Introducing sets](#sets)
    * [Introducing formatted strings](#fstrings)
    * [+= syntax](#plus-equals)
    * [Type Exercises](#type-ex)
* [2.2 Function syntax](#functions)
* [2.3 Control](#control)
    * [`if` problems](#if)
    * [`for` loop problems](#for)
    * [`while` loop problems](#while)
* [2.4 Accessing packages](#packages)
    * [e.g. `itertools`](#itertools)
* [2.5 Introducing `numpy`](#intro-numpy)
    * [Creating 1D `numpy` arrays](#create-arrays)
    * [Basic operations with numbers](#numbers)
    * [Array properties and dtype](#dtype)
    * [Manipulating arrays](#manipulating)
    * [Dealing with NaNs](#NaN)
    * [Univariate operations with arrays](#univariate-ops)
    * [Bivariate operations with arrays](#bivariate-ops) 
    * [Subtleties: views vs copies](#subtleties)
    * [`numpy` exercises](#numpy-exercises) 
* [2.6 Introducing `scipy`](#intro-scipy)
    * [`scipy` exercises](#scipy-exercises)

## 2.1 Python variable types <a name="python_types">
    
Last class, we introduced the fundamental variable types that python uses

* Numbers
* Strings (and formatted strings)
* Lists
* Booleans (True / False)
* Tuples
* Dictionaries

Today we will review these and add one more

* Sets

### 2.1.1 Introducing sets <a name="sets">

There is one variable type built into Python that we did not discuss: Sets. Like a list or tuple it is a combination of other variables, but unlike these other types there is

1. There is no notion of the order (so no subscripting aka indexing)
2. It comes with functions that make sense for sets (intersection, union, etc)
    
Sets can be created from lists or tuples using the `set(.)` command.

In [2]:
a = [1,1,1,2,3,2,5,7,4,7,7, 10]

b = set(a)
b

{1, 2, 3, 4, 5, 7, 10}

In [3]:
b[0]

TypeError: 'set' object does not support indexing

or you can create them directly using curly brackets `{.}`

In [4]:
# EXERCISE

c = {3, 6, 7, 9, 10}

In [10]:
# EXERCISE
# What can we do with another set `c`? 
# Use jupyter's autofill command `TAB` to find out what functions there are. (Type `b.` and then 
# press `TAB`)

b.difference(c)

{1, 2, 4, 5}

In [14]:
# EXERCISE
# Note that many functions have FUNCTION_update version. What is the difference?
# Play around and find out. Make sure to check what `b` and `c` equal after you run your function


d = b.difference_update(c)

In [16]:
type(d)

NoneType

In [18]:
# EXERCISE
# Play around with defining and manipulating sets here using autocomplete. 




### 2.1.2 Introducting formatted strings <a name="fstring">

Very often, you want to be able to create strings that incorperates information from varaibles (for printing for example). These are called formatted strings and Python provides three ways of creating them.

1. % syntax
2. STRING.format syntax
3. f-string syntax

We're going to ignore (1) since this is mostly depreciated this point, and we're going to ignore (2) since (3) is way easier.

#### f-string syntax

Basically, you can insert the string version of variables in a string if you prepend`f` to the string and use `{ }` to surround the variable name. 

_Read the [python docs of string formatting](https://docs.python.org/3/tutorial/inputoutput.html#formatted-string-literals)_

In [17]:
age = 2

f"Ayla is {age} years old"

'Ayla is 2 years old'

You can even do calculations using python code

In [18]:
f"Ayla is {age} years old, but if you ask her she says she is almost {age+1}"

'Ayla is 2 years old, but if you ask her she says she is almost 3'

You can also ask python to format the way variables are included. For example, you can add padding 

In [19]:
f"Ayla is {age:10} years old"

'Ayla is          2 years old'

or specify the precision of a number

In [23]:
from math import pi

my_string = f"A circle's circumference divided by its diameter is around {pi:.3} \n\t but much closer to {pi:.20}"
print(my_string)

A circle's circumference divided by its diameter is around 3.14 
	 but much closer to 3.141592653589793116


There is a **lot** more you can ask Python to do in how it actually converts the variable to a string.To understand more read on [the format specifier mini-language](https://docs.python.org/3/library/string.html#formatspec). 

### 2.1.3 += Syntax <a name="plus-equals">

Very often, you want to modify a variable using an arithmatic operator (like `+`, `*`) etc. and resave that variable under the same name. You could write 

In [24]:
a = 5

a = a + 2
a

7

or you could use the syntax `+=`

In [55]:
a = 5

a += 2
a

7

In [28]:
a = 5

# Try seeing what other `?=` operators there are.

a += 2
a

7

### 2.1.4 Variable type excrcises <a name="type-ex">

In [31]:
# EXERCISE
# Find a list method to sort the list below

r = [1, 5, 7, 1, 3, 5, 7]


r.sort(reverse=True)
r

[7, 7, 5, 5, 3, 1, 1]

In [42]:
# EXERCISE
# find a string method that you can use to extract the file extension from the file name below. 

file_name = 'numpy.rocks.jpeg'

index = file_name.rfind(".")
extension = file_name[index+1:]
print(extension)

file_name.split(".")
extension2 = file_name.split('.')[-1]
print(extension2)

jpeg
jpeg


## 2.2 Function syntax <a name="function">

In [48]:
def function_name(arg1, arg2, keyword1=default1, keyword2=default2):
    return output 

NameError: name 'default1' is not defined

In [49]:
def function_name(*args, keyword1=default, **kwargs):
    # args is a tulple 
    # kwargs is a dictionary of key value pairs
    return output

NameError: name 'default' is not defined

In [43]:
def counting_args(*args):
    return len(args)

In [46]:
counting_args(2)

1

## 2.3 Control <a name="control">

### 2.3.1 `if` exercises <a name="if">

In [58]:
# PROBLEM
# Write a script below that prints "even" if `a` is even and "odd" if it is odd. 
# Hint: use the modulo operator %
# next wrap this in a function called check_parity

def check_parity(num, returnbool=False):
    # checking the parity 
    parity = num%2 

    # returning the parity to the user
    if (parity==0):
        if returnbool:
            return(True)
        else:
            return('even')
    elif (parity='cat'):
        print('huh?')
    else: # parity = 1
        if returnbool:
            return(False)
        else:
            return('odd')

num=6
check_parity(num, returnbool=True)

True

In [60]:
# PROBLEM
# Write a Python program to print the mean, median, and mode of three given numbers, `a`, `b`, `c`. 
# Have it print the output nicely using f-strings. 
# next wrap this in a function called stat, include a keyword argument to pick which stat (mean, median, and mode) you want.

a = 3
b = 7
c = 4

mean = (a + b + c) / 3. 
print(f"Mean is {mean:.3}")

if a == b:
    median = a
    mode = a
elif b == c:
    median = b
    mode = b
elif (a<b):
    if c??????
    ....
    


Mean is 4.67


### 2.3.2 `for` loop exercises <a name="for">

In [ ]:
# EXERCISE 
# Write a Python program to print each element of the list and how often it appears
# Hint: lists have methods of counting counting the number of items. Think about how sets might help you here.  

r = [1, 5, 7, 1, 3, 5, 7]


for i in set(r):
    ...




In [63]:
# for pairs of objects use zip to iterate over both 

a = range(0, 3)
b = ['Amar', 'Terra', 'Nick']

for num, name in zip(a, b):
    print(num, name)
    
for num, name in enumerate(b):
    print(num, name)

0 Amar
1 Terra
2 Nick
0 Amar
1 Terra
2 Nick


In [45]:
# EXERCISE 
# Use list comprehension syntax to construct a list that squares each element of the list `nums` below

nums = [-2.4, 1.2, 5.7, -5, 4.3]




In [68]:
# EXERCISE 
# Use list comprehension syntax with if to construct a list that squares each positive element of the list `nums` below
# and ignores all negative items

nums = [-2.4, 1.2, 5.7, -5, 4.3]

num_squares = [i**2 for i in nums]
num_squares

num_squares_pos = [i**2 for i in nums if i > 0]
num_squares_pos

[1.44, 32.49, 18.49]

In [ ]:
# PROBLEM 
# Write a Python program to print the mean, median, and mode of a list `nums` of arbitrary length.
# Have it print the output nicely using f-strings. 

nums = [1, 1, 3, 5.7, 7, 8.3, 4.6, 5] 






### 2.3.3 `while` loop exerscises <a name="while">

In [ ]:
# PROBLEM 
# Write a while loop that spits out Fibonacci sequence up until 100. 

1, 1, 2, 3, 5, ...
    





## 2.4 Accessing packages <a name="packages">

You can acess packages using 
* `import...`: to import a package under its original name 
* `import...as...`: to importpackage under a new name
* `from...import...`: to import particular functions from a package into your namespace without importing the whole package. 

Technically, there is one more way but the Python community will be very, very angry with you if you do this (and you **don't** want to see the Python community get angry).

* `from...import *` to import all functions from a package into your namespace.
    
The Python distribution comes with a lot of submoidules. To get used to accessing packages and looking things up we'll play with two.

## 2.4.1 e.g. itertools <a name="itertools">

This is a package for common tasks one enounters when they want to iterate over a collection of objects. 

In [37]:
# EXERCISE 
# Find a function in the itertools package that allows you to iterate over every combination of one element in `A` and one in `B` 
# (e.g. (1, 'y')). Import it and use list comprehension to construct a list of all combinations.

A = [1, 2, 3]
B = ['x', 'y', 'z']


from itertools import function_name 

function_name()

import itertools as it

it.function_name()

...


## 2.5 Introduction to `numpy` <a name="intro-numpy">
    
`numpy` is the heart of using python for fast, efficient data processing. Python has many advantages, but it was not optimized for data manipulation - instead it was optimized for ease of use and flexiblity. Specifically, the way that python stores sets is not efficient for computations. Each element of a list is really a "pointer" to a memeory location that contains the object in question. These locations could be all over the place so as you can imagine if you need to conduct operations that require manipulating many elements at the same time this will be very slow as the program must constantly search all over memory to complete the task. 
    
`numpy` introduces the notion of an `array` which stores elements sequentially in memory for fast processing. These arrays are typically numbers but they can contain any other type of python object and even custom types (see [dtype section](#dtype)). Furthermore, these arrays can be _multidimensional_ (e.g. 2D like a matrix, 3D etc.) 
    
In addition to `arrays` numpy comes with efficient versions of many basic mathematical expressions (i.e. `np.cos`, `np.exp`, etc.) and constants (`np.pi` and `np.e`)
    
    
Much of what is below comes from existing websites
* [Numpy Beginners Tutorial](https://numpy.org/doc/stable/user/absolute_beginners.html)
* [Numpy Tutorial on Linear Algebra](https://numpy.org/doc/stable/user/tutorial-svd.html)
    
If you are familiar with MatLab you may want to look at [NumPy for MatLab users](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html).
    
Typically when numpy is imported it is renamed `np` so that you aren't stuck typing `numpy` every time you want to do anything.

In [70]:
# Let's go!

import numpy as np

### 2.5.1 Creating `numpy` arrays <a name="create-arrays">
    
There are many ways to create numpy arrays:
* `np.array(.)` 
* `np.zeros(.)` 
* `np.ones(.)`
* `np.full(.)`
* `np.empty(.)` 
* `np.arange(.)`
* `np.linspace(.)`
    
`np.array(.)` converts another list object to an array

In [71]:
# Creating an array from a list

a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [72]:
# They can be indexed just like lists

print(a[0:4])
print(a[-1])

[1 2 3 4]
6


They can also be indexed in really useful ways that lists can't. For example, if you wanted to spit out the 1st, 3rd, and 4th elements of a list you might try

In [73]:
# Oops

a = [10,20,30,40,50]
a[[1,3,4]]

TypeError: list indices must be integers or slices, not list

In [74]:
# But if you make `a` an array....

a = np.array([10,20,30,40,50])
a[[1,3,4]]

array([20, 40, 50])

The `==` operator also acts _on each element_ of the array **and** the array subscripting allows a Boolean list of equal length to be used. Putting these two facts together you can subselect elements of the array using conditions. 

In [78]:
print(a==10)
print(a[a==10])

ind = (a==10)
a[ind]

[ True False False False False]
[10]


array([10])

If you want to know is _any_ elements of the array or _all_ elements of the array meet a critera use the `.any()` or `.all()` methods. 

In [7]:
print((a > 20).any())
print((a > 20).all())

True
False


In [82]:
# You can use a list of lists to create a multidimensional array
# NOTE: each of the sub-lists MUST be the same length.

a = np.array([[1, 2, 3], [10, 12, 13]])
a

array([[ 1,  2,  3],
       [10, 12, 13]])

In [84]:
# Indexing uses two coordinates ARRAY[ROW, COL]
# can also ask numpy to spit out an entire row or column using `:`

print(a[0,1])
print(a[1,:])
print(a[:,2])

2
[10 12 13]
[ 3 13]


`np.ones(.)`, `np.zeros(.)`, `np.empty(.)` take a number or a tuple to create an element 

In [10]:
# ones and zeros do exactly what you might expect
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [11]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

`np.empty(.)` is a bit more subtle. Use this command if you know you'll be replacing the elements. It just crates an array without clearning memory so the numbers a garbage. It's faster than the other operations. 

In [12]:
np.empty(10)

array([ 1.72723371e-077, -2.00389702e+000,  2.47032823e-323,
        0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
        1.72723371e-077, -1.73059924e-077,  1.21518768e-046,
        7.64704033e-309])

`np.full(., .)` creates arrays filled with a specific values. 

In [13]:
np.full(10, 3.14)

array([3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14])

In [87]:
# All of these functions have a function_like version. Use jupyter's `Shift+TAB` or `Contextual Help` fratures to figure out what they do. 

a = np.ones((10, 3, 2))
np.full_like(a, 10)

array([[[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]],

       [[10., 10.],
        [10., 10.],
        [10., 10.]]])

You can also generate sequential numbers one of two ways: `np.arange(.)`, `np.linspace(.)`. `np.arange(.)` works just like range but it creates a numpy array. Just like range the initial number is inlcuded but final number is not. 

In [90]:
# np.arange(START, STOP, STEP)

np.arange(1,15,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
np.arange(1,15,2)

array([ 1,  3,  5,  7,  9, 11, 13])

`np.linspace(START, END, LENGTH)` is similar but you specify how long you'd like the array to be with the third argument. Also note that the linspace command creates an array that **includes** the initial and final values. 

In [17]:
np.linspace(1, 15, 100)

array([ 1.        ,  1.14141414,  1.28282828,  1.42424242,  1.56565657,
        1.70707071,  1.84848485,  1.98989899,  2.13131313,  2.27272727,
        2.41414141,  2.55555556,  2.6969697 ,  2.83838384,  2.97979798,
        3.12121212,  3.26262626,  3.4040404 ,  3.54545455,  3.68686869,
        3.82828283,  3.96969697,  4.11111111,  4.25252525,  4.39393939,
        4.53535354,  4.67676768,  4.81818182,  4.95959596,  5.1010101 ,
        5.24242424,  5.38383838,  5.52525253,  5.66666667,  5.80808081,
        5.94949495,  6.09090909,  6.23232323,  6.37373737,  6.51515152,
        6.65656566,  6.7979798 ,  6.93939394,  7.08080808,  7.22222222,
        7.36363636,  7.50505051,  7.64646465,  7.78787879,  7.92929293,
        8.07070707,  8.21212121,  8.35353535,  8.49494949,  8.63636364,
        8.77777778,  8.91919192,  9.06060606,  9.2020202 ,  9.34343434,
        9.48484848,  9.62626263,  9.76767677,  9.90909091, 10.05050505,
       10.19191919, 10.33333333, 10.47474747, 10.61616162, 10.75

`numpy`'s random subpackage also includes ways of creating arrays with random values. 

* `np.random.rand(SHAPE)`: create an array of numbers randomly drawn from the uniform distribution between 0 and 1
* `np.radom.normal(MEAN, STD, SIZE)`: create an array of numbers ranomdly drawn from the normal distribution with mean = MEAN and standard deviation = STD

In [19]:
np.random.rand(10)

array([0.16107924, 0.46138581, 0.84169722, 0.74788522, 0.33576545,
       0.67227811, 0.3438143 , 0.28527916, 0.21011425, 0.62332055])

In [3]:
np.random.normal(1, 1, 10)

array([ 1.49555856,  0.05535424,  0.80209243,  1.86000699,  1.5123017 ,
        0.78244057,  1.4744679 , -1.22436699,  1.49711188,  0.58870249])

In [18]:
# EXERCISE
# Create some arrays and use the Boolean subscripting (e.g. a[a >20]) to select elements of the array. 






### 2.5.2 Basic operations with numbers <a name="numbers">
    
You can do standard arithmatic with numbers and arrays (`+`, `*`, etc.). This applies the operation pointwise across each element of the array 

In [20]:
10*np.arange(1,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
10*np.arange(1,10) + 1

array([11, 21, 31, 41, 51, 61, 71, 81, 91])

You can apply any function you want across an array. 

In [82]:
def squareer(x):
    return x**2

a = np.arange(1,100)
squareer(a)

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

### 2.5.3 Array properties and dtype <a name="dtype">

To find the shape and number of dimensions of an array you can use the `ARRAY.shape` and `ARRAY.ndim` variables. 

In [90]:
a = np.empty((10,5))

print(a.shape)
print(a.ndim)

(10, 5)
2


In order to store arrays efficiently, numpy needs to know something about what type of data is in an array. This is called the array's `dtype`. To access an array's dtype use the `ARRAY.dtype` variable. 

In [110]:
a.dtype

dtype('int64')

In [92]:
# EXERCISE
# Try to interpret the number in the dtype for the array below

np.array(['hi', 'there'])

array(['hi', 'there'], dtype='<U5')

### 2.5.4 Maniplulating arrays <a name="manipulating">
    
Numpy provides **a lot** of ways to manipulate arrays. [Check out the API reference here.](https://numpy.org/devdocs/reference/routines.array-manipulation.html) Here we will only look at a few key ones
    
* `ARRAY.reshape(a, newshape)`, `ARRAY.flatten(.)`, `np.transpose(a)`
* `np.concatenate(.)`, `np.hstack(.)`, `np.c_`, `np.vstack(.)`, `np.r_`, `np.split(.)`
* `ARRAY.sort(.)`, `ARRAY.argsort(.)`, `ARRAY.searchsorted(.)`

In [94]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
b = a.reshape((5,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [96]:
c = b.reshape((2,5))
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

If you want to "flatten" a multidimensional array to a 1D array can use `ARRAY.reshape(-1)` or `ARRAY.flatten()`

In [97]:
print(f"flatten\n{c.flatten()}\n")
print(f"reshape\n{c.reshape(-1)}\n")

flatten
[0 1 2 3 4 5 6 7 8 9]

reshape
[0 1 2 3 4 5 6 7 8 9]



In [53]:
# np.concatenate, np.vstack and np.r_ all allow you to combine arrays "vertically" (along axis 0)

a = np.ones((3, 2))
b = np.ones((3, 2))

print(f"concatenate\n {np.concatenate([a, b], axis=0)}\n")
print(f"hstack\n{np.vstack([a, b])}\n")
print(f"r_\n{np.r_[a, b]}\n")

concatenate
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

hstack
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

c_
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]



In [50]:
# np.concatenate, np.hstack, and np.c_ all allow you to combine arrays "horizontally" (along axis 1)

a = np.ones((3, 2))
b = np.ones((3, 2))

print(f"concatenate\n {np.concatenate([a, b], axis=1)}\n")
print(f"hstack\n{np.hstack([a, b])}\n")
print(f"c_\n{np.c_[a, b]}\n")

concatenate
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

hstack
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

c_
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



In [8]:
# EXERCISE
# Build a 2D array where the first row is the first 10 multiples of 1, 
# the second is the first 10 multiples of 2, 
# ..., and the last row is the first 10 multiples of 5. 

import numpy as np

my_work_array=np.array([1,2,3,4,5,6,7,8,9,10])

array1 = my_work_array*1
array2 = my_work_array*2
array3 = my_work_array*3
array4 = my_work_array*4
array5 = my_work_array*5

print(f"2D array \n{np.vstack([array1, array2, array3])}\n")

#---------------

my_work_array=np.arange(1, 11)

arrays = 5 * [None]
for i in range(1,6):
    arrays[i-1] = i * my_work_array

print(np.vstack(arrays))

my_work_array=np.arange(1, 11)

#--------------

arrays = [] #unkown length
for i in range(1,6):
    arrays.append(i * my_work_array)

print(np.vstack(arrays))

#--------------

arrays = [i*my_work_array for i in range(1,6)]
new_array = np.vstack(arrays)

2D array 
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]
 [ 3  6  9 12 15 18 21 24 27 30]]

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]
 [ 3  6  9 12 15 18 21 24 27 30]
 [ 4  8 12 16 20 24 28 32 36 40]
 [ 5 10 15 20 25 30 35 40 45 50]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 2  4  6  8 10 12 14 16 18 20]
 [ 3  6  9 12 15 18 21 24 27 30]
 [ 4  8 12 16 20 24 28 32 36 40]
 [ 5 10 15 20 25 30 35 40 45 50]]


In [7]:
names = ["AK", "BA", "AO", "CB", "EM", "MJ", "TS", "NL", "AZ"]

first_initials = [name[0] for name in names if name[0] not in ["B", "A"]]
first_initials

['C', 'E', 'M', 'T', 'N']

To sort arrays use the `np.sort(ARRAY)`, `np.argsort(ARRAY)`, `np.searchsorted(ARRAY, VALUE)` commands. `ARRAY.sort()` **does not return anything**. It simply sorts and resaves a a sorted version of an array (i.e. it acts "in-place")

In [98]:
a = np.array([3, 7, 4, 6, 1, 0, 8, 9, 3])

a.sort()
a

array([0, 1, 3, 3, 4, 6, 7, 8, 9])

There is a command to ranomly shuffle arrays that operates in the same way. 

In [101]:
# Try re-running this to see that `a` is shuffled differently each time. 

np.random.shuffle(a)
a

array([4, 0, 3, 6, 3, 9, 8, 7, 1])

`np.argsort(ARRAY)` returns a list of indicies that _would_ sort `ARRAY`

In [123]:
a = 10*np.arange(0,9)
np.random.shuffle(a)
a

array([70, 50, 20, 60, 30, 40,  0, 80, 10])

In [10]:
# EXCERSISE
# Using argsort, sort the names accoring to their birth month. 

names = np.array(['Anne', 'Abel', 'Adam', 'Ali', 'Allison'])
birth_months = np.array([2, 7, 1, 11, 5])





In [25]:
birth_months > 5

array([False,  True, False,  True, False])

In [29]:
# What if you want to 1. select a sebset by a criteria, 
# 2. sort the remianing values

early_names = names[birth_months < 11]
early_birth_months = birth_months[birth_months < 11]

early_names[early_birth_months.argsort()]

#-----------

names[birth_months < 11][birth_months[birth_months < 11].argsort()]


array(['Adam', 'Anne', 'Allison', 'Abel'], dtype='<U7')

In [22]:
new_names = []
for index in birth_months.argsort():
    new_names.append(names[index])
print(new_names)

print([names[index] for index in birth_months if birth_month[index] > 5])


['Adam', 'Anne', 'Allison', 'Abel', 'Ali']
['Adam', 'Anne', 'Allison', 'Abel', 'Ali']


In [16]:
np.argsort(birth_months)

array([2, 0, 4, 1, 3])

### 2.5.5 Dealing with NaN <a name="NaN">

`numpy` includes functionality for missing data via `np.nan` (Not a number) and extremely large numebrs with `np.Infinity`. Arrays can include these values along with other objects. Numpy also includes many functions for dealing with arrays that have NaNs:

* `np.nan_to_num(ARRAY)`: replaces np.nans with 0 and np.Infinity with a large number. (Can change the value with nan= keyword argument)
* `np.nanmean(ARRAY)`: mean ignoring nans



In [103]:
a = np.array([1.2, 3.4, np.nan, 10.1])

In [5]:
np.nan_to_num(a)

array([ 1.2,  3.4,  0. , 10.1])

In [9]:
np.nan_to_num(a, nan=100)

array([  1.2,   3.4, 100. ,  10.1])

In [104]:
# taking the regular means results in a nan value

a.mean()

nan

In [8]:
# using nanmean ignoes the np.NaN. 

np.nanmean(a)

4.8999999999999995

### 2.5.6 Univerate operations <a name="univariate-ops">

Numpy provides a **lot** of functions. Go to [the numpy reference](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs) to see what is available. Most important ones are `np.mean`, `np.sum`, `np.maximum`, `np.minimum`, etc. 

**EXERCISE**

Find the values of 

$$2\cos(x/\pi +3) -5$$

for 

$$ x = 0, .5, 1.0, 1.5, \dots, 12$$

In [35]:
# EXERCISE
# Find the maximum value of each column of the array below. 
# Also find the maximum of each row

A = np.array([[1, 3, 4, 6, 2],
             [ 4, 10, -5, 3, 4], 
             [-1, 2, 4, 1, 7]])




A.mean(axis=0)

array([1.33333333, 5.        , 1.        , 3.33333333, 4.33333333])

### 2.5.7 Bivariate operations <a name="bivariate-ops">

`numpy` also provides a number of ways to combine arrays. Standard operators like `*` and `+` operate _pointwise_. In other words the two arrays must bethe same size and these operators combine each entry. 

In [36]:
# EXERCISE
# Define two 2D arrays of the same size and combine them 
# using pointwise operators


#-------------------
B = np.array([1,2,3])
C = np.array([5,10,15])
print(B + C)


#------------------



array([ 6, 12, 18])

Of course, very often we want to do _matrix_ multiplication. This is represented in Python 3 by the `@` symbol. 

In [105]:
a = np.random.rand(4,3)
a

array([[6.63108246e-01, 1.62049698e-04, 9.24321936e-01],
       [4.67295051e-01, 8.48641985e-01, 6.77422139e-01],
       [4.59392603e-01, 6.57151357e-02, 5.16733748e-01],
       [1.33045597e-01, 2.93061717e-01, 6.26867226e-01]])

In [106]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [56]:
# days X products
sales = np.array([[3, 0, 0], 
                  [2, 2, 0], 
                  [1, 0, 1],
                  [0, 4, 1],
                  [0, 1, 4]])

sales_2 = np.array([[3, 2, 1, 0, 0], 
                    [0, 2, 0, 4, 1],
                    [0, 0, 1, 1, 4]])

# products X cost
# 1D array
prices = np.array([3, 5, 1])

# 2D array with one column
prices_wtf = np.array([[3], [5], [1]])
# 2D array with one row
prices_wtf_2 = np.array([[3, 5, 1]])



price_labels = np.array(["cookies", "brownies", "apples"])
                    
prices_w_taxes = np.array([[3, 5, 1], 
                           [0.3, 0.5, 0]])

In [46]:
sales.shape

(5, 3)

In [47]:
prices.shape

(3,)

In [49]:
# Oops 
# Why doesn't this work? products does not line up with itself 

prices @ sales

ValueError: shapes (3,) and (5,3) not aligned: 3 (dim 0) != 5 (dim 0)

In [51]:
# This works

sales @ prices

array([ 9, 16,  4, 21,  9])

In [53]:
# Comparing 2D array shapes 

prices_wtf.shape

(3, 1)

In [57]:
prices_wtf_2.shape

(1, 3)

In [58]:
sales.shape

(5, 3)

In [59]:
# How do I multiply these?

sales @ prices_wtf

array([[ 9],
       [16],
       [ 4],
       [21],
       [ 9]])

In [60]:
# How do I do this calculation with taxes?

# sales @ prices_w_taxes?
# prices_w_taxes @ sales?
# Something else?



In [66]:
prices_w_taxes.transpose().shape

(3, 2)

In [65]:
prices_w_taxes.swapaxes(0, 1)

array([[3. , 0.3],
       [5. , 0.5],
       [1. , 0. ]])

In [63]:
sales.shape

(5, 3)

In [68]:
# Answer in days X type of cost
sales @ prices_w_taxes.transpose()

array([[ 9. ,  0.9],
       [16. ,  1.6],
       [ 4. ,  0.3],
       [21. ,  2. ],
       [ 9. ,  0.5]])

In [75]:
pr = {"cookies": 0, "brownies": 1, "apples": 2}
days = {"Mon": 0, "Tue": 1, "Wed": 2, "Thus":3, "Fri":4}
pr["cookies"]

0

In [74]:
sales

array([[3, 0, 0],
       [2, 2, 0],
       [1, 0, 1],
       [0, 4, 1],
       [0, 1, 4]])

In [76]:
sales[days["Mon"], pr["cookies"]]

3

    100% |████████████████████████████████| 706kB 4.1MB/s eta 0:00:01
    100% |████████████████████████████████| 10.5MB 1.5MB/s eta 0:00:01 42% |█████████████▋                  | 4.5MB 41.9MB/s eta 0:00:01�███████▎           | 6.6MB 39.9MB/s eta 0:00:01███████████████████████▊    | 9.1MB 44.8MB/s eta 0:00:01
    100% |████████████████████████████████| 788kB 4.5MB/s eta 0:00:01 |█████████▋                      | 235kB 45.8MB/s eta 0:00:01
  Found existing installation: pandas 0.23.4
    Uninstalling pandas-0.23.4:
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/ihome/crc/install/python/miniconda3-3.7/lib/python3.7/site-packages/pandas-0.23.4.dist-info/INSTALLER'
Consider using the `--user` option or check the permissions.

You are using pip version 18.0, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [79]:
import xarray as xa

ModuleNotFoundError: No module named 'xarray'

### 2.5.8 Subtleties: views vs copies <a name="subtleties">

* `np.copy(.)` or `ARRAY.copy()`
* `np.split(.)` vs `np.array_split(.)`

### 2.5.8 `numpy` exercises <a name="numpy-exercises">

In [ ]:
# create three matricies and conatenate

## 2.6 Introduction to `scipy` <a name="scipy-intro">
    
`scipy` is a package which contains a number of convinience functions for mathematics and data analysis
    
* **scipy.cluster**: Vector quantization / Kmeans
* **scipy.constants**: Physical and mathematical constants
* **scipy.fftpack**: Fourier transform
* **scipy.integrate**: Integration routines
* **scipy.interpolate**: Interpolation
* **scipy.io**: Data input and output
* **scipy.linalg**: Linear algebra routines
* **scipy.ndimage**: n-dimensional image package
* **scipy.odr**: Orthogonal distance regression
* **scipy.optimize**: Optimization
* **scipy.signal**: Signal processing
* **scipy.sparse**: Sparse matrices
* **scipy.spatial**: Spatial data structures and algorithms
* **scipy.special**: Any special mathematical functions
* **scipy.stats**: Statistics

In [23]:
import scipy as sp

### 2.6.1 `scipy` exercises <a name="scipy-exercises">

In [ ]:
# EXCERSISE
# scipy show and tell: Pick a submodule of interest, use the jupyter autocomplete functionality or the scipy docs to find a 
# function of interest udnerstand its arguments and try to do a calculation using that function. Play around with the arguments.  







